set -g status-style "bg=#c7c9cc,fg=#111214"

set -g status-left "#[fg=#111214,bg=#c7c9cc] sync-vault "

set -g status-right "#[fg=#777b82,bg=#c7c9cc] %H:%M "

# Window list
setw -g window-status-format "#[fg=#777b82,bg=#c7c9cc] #I:#W "
setw -g window-status-current-format "#[fg=#111214,bg=#c7c9cc,bold] #I:#W "

set -g status-left-length 30
set -g status-right-length 30

