"$schema" = 'https://starship.rs/config-schema.json'

format = '[ $username ❯ $directory $git_branch ](#111214 bg:#c7c9cc)$line_break$character'

[username]
show_always = true
format = '$user'

[directory]
format = '$path'
truncation_length = 1
truncate_to_repo = false

[git_branch]
format = '$symbol $branch'
symbol = '󰊢'

[line_break]
disabled = false

[character]
success_symbol = '❯'
error_symbol = '❯'
vimcmd_symbol = '❮'

