#!/bin/bash

start() {
  sudo systemctl start docker.socket
  sudo systemctl start docker.service
}

stop() {
  sudo systemctl stop docker.service
  sudo systemctl stop docker.socket
}

status() {
  systemctl status docker
  systemctl status docker.socket
}

"$@"
