#!/bin/bash

WALLPAPER_DIR="$HOME/Pictures/Wallpapers"
THUMB_DIR="$HOME/.cache/wallpaper-thumbnails"

mkdir -p "$THUMB_DIR"

find "$WALLPAPER_DIR" -type f \( \
    -iname "*.png" -o \
    -iname "*.jpg" -o \
    -iname "*.jpeg" -o \
    -iname "*.webp" \
\) |
while read -r wallpaper; do
    filename=$(basename "$wallpaper")
    thumbnail="$THUMB_DIR/$filename"

    magick "$wallpaper" \
        -thumbnail '400x250^' \
        -gravity center \
        -extent 400x250 \
        "$thumbnail"

    printf '%s\0icon\x1f%s\n' "$filename" "$thumbnail"
done |
rofi -dmenu \
    -show-icons \
    -p "Wallpaper" \
    -theme-str '
        window {
            width: 80%;
            height: 80%;
        }

        mainbox {
            children: [ inputbar, listview ];
            spacing: 10px;
        }

        listview {
            columns: 3;
            lines: 2;
            spacing: 10px;
            fixed-height: true;

            cycle: true;
            dynamic: true;
        }

        element {
            orientation: vertical;
            padding: 0px;
            spacing: 0px;

            children: [
                element-icon
            ];
        }

        element-icon {
            size: 250px;
        }
    ' |
while read -r selected; do
    [ -z "$selected" ] && exit 0

    swww img "$WALLPAPER_DIR/$selected"
done
