[bar/main]
monitor = ${env:MONITOR}

width = 100%
height = 28

background = #20202A
foreground = #C6D0E9

font-0 = "FiraCode Nerd Font Mono:size=10"
font-1 = "Noto Color Emoji:size=10"

modules-left = i3
modules-center = date
modules-right = setxkbmap music sep volume sep battery

module-margin = 1

wm-restack = i3


[module/sep]
type = custom/text
content = "  "
foreground = #C6D0E9


[module/i3]
type = internal/i3
format = <label-state>
index-sort = true
wrapping-scroll = false

label-focused = %name%
label-focused-background = #A8B6D0
label-focused-underline = #cddbf9
label-focused-foreground = #2E3440
label-focused-padding = 1

label-unfocused = %name%
label-unfocused-foreground = #8B949E
label-unfocused-background = #1b1b23
label-unfocused-padding = 1

label-visible = %name%
label-visible-background = #161b22
label-visible-foreground = #C6D0E9
label-visible-padding = 1


[module/date]
type = internal/date
interval = 5

date = %H:%M
label = %date%
label-foreground = #C6D0E9
label-background = #20202A


; [module/music]
; type = custom/script
; exec = playerctl metadata --format "  {{artist}} - {{title}}"
; ; exec = ~/.config/polybar/scripts/mpd-status.sh
; interval = 2
; label-foreground = #cddbf9
; label-background = #20202A

[module/setxkbmap]
type = "custom/script"
exec = ~/.config/polybar/scripts/kb-layout.sh

[module/music]
type = custom/script
exec = ~/.config/polybar/scripts/music.sh
interval = 2

label-foreground = #cddbf9
label-background = #20202A

click-left = mpc toggle || playerctl play-pause
click-right = mpc next || playerctl next
click-middle = mpc prev || playerctl previous

[module/volume]
type = internal/alsa

format-volume = <label-volume>
label-volume =  %percentage%%
label-muted =  muted
label-foreground = #caf6bb
label-background = #20202A

click-right = pavucontrol


[module/battery]
type = internal/battery
battery = BAT0
adapter = AC0
full-at = 98

format = <label>

label-charging =  %percentage%%
label-discharging =  %percentage%%
label-full = 
label-foreground = #E6DFB8
label-background = #20202A


